In [17]:
import pandas as pd
print(pd.__version__)

2.3.3

In [18]:
df_activity = pd.read_csv("../Original_Data/Fitabase Data 4.12.16-5.12.16/dailyActivity_merged.csv")

In [19]:
df_activity.head()

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
0,1503960366,4/12/2016,13162,8.50,8.50,0.0,1.88,0.55,6.06,0.0,25,13,328,728,1985
1,1503960366,4/13/2016,10735,6.97,6.97,0.0,1.57,0.69,4.71,0.0,21,19,217,776,1797
2,1503960366,4/14/2016,10460,6.74,6.74,0.0,2.44,0.40,3.91,0.0,30,11,181,1218,1776
3,1503960366,4/15/2016,9762,6.28,6.28,0.0,2.14,1.26,2.83,0.0,29,34,209,726,1745
4,1503960366,4/16/2016,12669,8.16,8.16,0.0,2.71,0.41,5.04,0.0,36,10,221,773,1863

In [20]:
df_activity.shape

(940, 15)

In [25]:
df_activity.columns

Index(['Id', 'ActivityDate', 'TotalSteps', 'TotalDistance', 'TrackerDistance',
       'LoggedActivitiesDistance', 'VeryActiveDistance',
       'ModeratelyActiveDistance', 'LightActiveDistance',
       'SedentaryActiveDistance', 'VeryActiveMinutes', 'FairlyActiveMinutes',
       'LightlyActiveMinutes', 'SedentaryMinutes', 'Calories'],
      dtype='object')

In [28]:
df_activity.isnull

<bound method DataFrame.isnull of              Id ActivityDate  TotalSteps  TotalDistance  TrackerDistance  \
0    1503960366    4/12/2016       13162       8.500000         8.500000
1    1503960366    4/13/2016       10735       6.970000         6.970000
2    1503960366    4/14/2016       10460       6.740000         6.740000
3    1503960366    4/15/2016        9762       6.280000         6.280000
4    1503960366    4/16/2016       12669       8.160000         8.160000
..          ...          ...         ...            ...              ...
935  8877689391     5/8/2016       10686       8.110000         8.110000
936  8877689391     5/9/2016       20226      18.250000        18.250000
937  8877689391    5/10/2016       10733       8.150000         8.150000
938  8877689391    5/11/2016       21420      19.559999        19.559999
939  8877689391    5/12/2016        8064       6.120000         6.120000

     LoggedActivitiesDistance  VeryActiveDistance  ModeratelyActiveDistance  \
0                         0.0                1.88                      0.55
1                         0.0                1.57                      0.69
2                         0.0                2.44                      0.40
3                         0.0                2.14                      1.26
4                         0.0                2.71                      0.41
..                        ...                 ...                       ...
935                       0.0                1.08                      0.20
936                       0.0               11.10                      0.80
937                       0.0                1.35                      0.46
938                       0.0               13.22                      0.41
939                       0.0                1.82                      0.04

     LightActiveDistance  SedentaryActiveDistance  VeryActiveMinutes  \
0                   6.06                     0.00                 25
1                   4.71                     0.00                 21
2                   3.91                     0.00                 30
3                   2.83                     0.00                 29
4                   5.04                     0.00                 36
..                   ...                      ...                ...
935                 6.80                     0.00                 17
936                 6.24                     0.05                 73
937                 6.28                     0.00                 18
938                 5.89                     0.00                 88
939                 4.25                     0.00                 23

     FairlyActiveMinutes  LightlyActiveMinutes  SedentaryMinutes  Calories
0                     13                   328               728      1985
1                     19                   217               776      1797
2                     11                   181              1218      1776
3                     34                   209               726      1745
4                     10                   221               773      1863
..                   ...                   ...               ...       ...
935                    4                   245              1174      2847
936                   19                   217              1131      3710
937                   11                   224              1187      2832
938                   12                   213              1127      3832
939                    1                   137               770      1849

[940 rows x 15 columns]>

In [29]:
df_activity.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 940 entries, 0 to 939
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Id                        940 non-null    int64
 1   ActivityDate              940 non-null    object
 2   TotalSteps                940 non-null    int64
 3   TotalDistance             940 non-null    float64
 4   TrackerDistance           940 non-null    float64
 5   LoggedActivitiesDistance  940 non-null    float64
 6   VeryActiveDistance        940 non-null    float64
 7   ModeratelyActiveDistance  940 non-null    float64
 8   LightActiveDistance       940 non-null    float64
 9   SedentaryActiveDistance   940 non-null    float64
 10  VeryActiveMinutes         940 non-null    int64
 11  FairlyActiveMinutes       940 non-null    int64
 12  LightlyActiveMinutes      940 non-null    int64
 13  SedentaryMinutes          940 non-null    int64
 14  Calories                  940 non-null    int64
dtypes: float64(7), int64(7), object(1)
memory usage: 110.3+ KB

In [33]:
df_activity.isnull().sum()

Id                          0
ActivityDate                0
TotalSteps                  0
TotalDistance               0
TrackerDistance             0
LoggedActivitiesDistance    0
VeryActiveDistance          0
ModeratelyActiveDistance    0
LightActiveDistance         0
SedentaryActiveDistance     0
VeryActiveMinutes           0
FairlyActiveMinutes         0
LightlyActiveMinutes        0
SedentaryMinutes            0
Calories                    0
dtype: int64

In [55]:
df_activity.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
935    False
936    False
937    False
938    False
939    False
Length: 940, dtype: bool

In [35]:
df_activity['ActivityDate'].head()

0    4/12/2016
1    4/13/2016
2    4/14/2016
3    4/15/2016
4    4/16/2016
Name: ActivityDate, dtype: object

In [37]:
df_activity["ActivityDate"].dtype

dtype('O')

In [38]:
df_activity['ActivityDate'] = pd.to_datetime(df_activity['ActivityDate'])

In [39]:
df_activity["ActivityDate"].dtype

dtype('<M8[ns]')

In [40]:
df_activity["ActivityDate"].min()

Timestamp('2016-04-12 00:00:00')

In [41]:
df_activity["ActivityDate"].max()

Timestamp('2016-05-12 00:00:00')

In [43]:
df_activity["Id"].nunique()

33

In [44]:
df_activity["Id"].value_counts().head()

Id
1503960366    31
1624580081    31
1844505072    31
1927972279    31
2022484408    31
Name: count, dtype: int64

In [45]:
df_activity["Id"].value_counts().min()

np.int64(4)

In [46]:
df_activity["Id"].value_counts().max()

np.int64(31)

In [47]:
df_activity["TotalSteps"].describe()

count      940.000000
mean      7637.910638
std       5087.150742
min          0.000000
25%       3789.750000
50%       7405.500000
75%      10727.000000
max      36019.000000
Name: TotalSteps, dtype: float64

In [51]:
df_activity[df_activity["TotalSteps"] == 0].shape

(77, 15)

In [52]:
df_activity[df_activity["TotalSteps"] == 0][["Id", "ActivityDate", "TotalSteps"]].head(10)

             Id ActivityDate  TotalSteps
30   1503960366   2016-05-12           0
104  1844505072   2016-04-24           0
105  1844505072   2016-04-25           0
106  1844505072   2016-04-26           0
112  1844505072   2016-05-02           0
117  1844505072   2016-05-07           0
118  1844505072   2016-05-08           0
119  1844505072   2016-05-09           0
120  1844505072   2016-05-10           0
121  1844505072   2016-05-11           0

In [53]:
df_activity[df_activity["TotalSteps"] == 0][
    ["Id", "ActivityDate", "TotalSteps", "Calories", "SedentaryMinutes"]
].head(15)

             Id ActivityDate  TotalSteps  Calories  SedentaryMinutes
30   1503960366   2016-05-12           0         0              1440
104  1844505072   2016-04-24           0      1347              1440
105  1844505072   2016-04-25           0      1347              1440
106  1844505072   2016-04-26           0      1347              1440
112  1844505072   2016-05-02           0      1348              1440
117  1844505072   2016-05-07           0      1347              1440
118  1844505072   2016-05-08           0      1347              1440
119  1844505072   2016-05-09           0      1347              1440
120  1844505072   2016-05-10           0      1347              1440
121  1844505072   2016-05-11           0      1347              1440
122  1844505072   2016-05-12           0       665               711
127  1927972279   2016-04-16           0      2064              1440
128  1927972279   2016-04-17           0      2063              1440
130  1927972279   2016-04-19           0      2063              1440
131  1927972279   2016-04-20           0      2063              1440

In [56]:
df_activity[df_activity["SedentaryMinutes"] == 1440].shape

(79, 15)

In [58]:
df_activity[df_activity["SedentaryMinutes"] == 1440][
    ["Id", "ActivityDate", "TotalSteps", "Calories", "SedentaryMinutes"]
].head(10)

             Id ActivityDate  TotalSteps  Calories  SedentaryMinutes
30   1503960366   2016-05-12           0         0              1440
104  1844505072   2016-04-24           0      1347              1440
105  1844505072   2016-04-25           0      1347              1440
106  1844505072   2016-04-26           0      1347              1440
112  1844505072   2016-05-02           0      1348              1440
117  1844505072   2016-05-07           0      1347              1440
118  1844505072   2016-05-08           0      1347              1440
119  1844505072   2016-05-09           0      1347              1440
120  1844505072   2016-05-10           0      1347              1440
121  1844505072   2016-05-11           0      1347              1440

In [63]:
df_activity[[
    "TotalDistance",
    "Calories",
    "VeryActiveMinutes",
    "FairlyActiveMinutes",
    "LightlyActiveMinutes",
    "SedentaryMinutes"
]].describe()

,TotalDistance,Calories,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes
count,940.000000,940.000000,940.000000,940.000000,940.000000,940.000000
mean,5.489702,2303.609574,21.164894,13.564894,192.812766,991.210638
std,3.924606,718.166862,32.844803,19.987404,109.174700,301.267437
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.620000,1828.500000,0.000000,0.000000,127.000000,729.750000
50%,5.245000,2134.000000,4.000000,6.000000,199.000000,1057.500000
75%,7.712500,2793.250000,32.000000,19.000000,264.000000,1229.500000
max,28.030001,4900.000000,210.000000,143.000000,518.000000,1440.000000

In [66]:
df_sleep = pd.read_csv(
    "../Original_Data/Fitabase Data 4.12.16-5.12.16/sleepDay_merged.csv"
)

In [67]:
df_sleep.head()

,Id,SleepDay,TotalSleepRecords,TotalMinutesAsleep,TotalTimeInBed
0,1503960366,4/12/2016 12:00:00 AM,1,327,346
1,1503960366,4/13/2016 12:00:00 AM,2,384,407
2,1503960366,4/15/2016 12:00:00 AM,1,412,442
3,1503960366,4/16/2016 12:00:00 AM,2,340,367
4,1503960366,4/17/2016 12:00:00 AM,1,700,712

In [68]:
df_sleep.shape

(413, 5)

In [69]:
df_sleep.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 413 entries, 0 to 412
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Id                  413 non-null    int64
 1   SleepDay            413 non-null    object
 2   TotalSleepRecords   413 non-null    int64
 3   TotalMinutesAsleep  413 non-null    int64
 4   TotalTimeInBed      413 non-null    int64
dtypes: int64(4), object(1)
memory usage: 16.3+ KB

In [70]:
df_sleep.columns

Index(['Id', 'SleepDay', 'TotalSleepRecords', 'TotalMinutesAsleep',
       'TotalTimeInBed'],
      dtype='object')

In [75]:
df_sleep.isnull().sum()

Id                    0
SleepDay              0
TotalSleepRecords     0
TotalMinutesAsleep    0
TotalTimeInBed        0
dtype: int64

In [77]:
df_sleep.duplicated().sum()

np.int64(3)

In [78]:
df_sleep[df_sleep.duplicated(keep=False)]

,Id,SleepDay,TotalSleepRecords,TotalMinutesAsleep,TotalTimeInBed
160,4388161847,5/5/2016 12:00:00 AM,1,471,495
161,4388161847,5/5/2016 12:00:00 AM,1,471,495
222,4702921684,5/7/2016 12:00:00 AM,1,520,543
223,4702921684,5/7/2016 12:00:00 AM,1,520,543
379,8378563200,4/25/2016 12:00:00 AM,1,388,402
380,8378563200,4/25/2016 12:00:00 AM,1,388,402

In [79]:
df_sleep = df_sleep.drop_duplicates()

In [80]:
df_sleep.duplicated().sum()

np.int64(0)

In [81]:
df_sleep.shape

(410, 5)

In [82]:
df_sleep['SleepDay'].dtype

dtype('O')

In [84]:
df_sleep.head()

,Id,SleepDay,TotalSleepRecords,TotalMinutesAsleep,TotalTimeInBed
0,1503960366,2016-04-12,1,327,346
1,1503960366,2016-04-13,2,384,407
2,1503960366,2016-04-15,1,412,442
3,1503960366,2016-04-16,2,340,367
4,1503960366,2016-04-17,1,700,712

In [88]:
df_sleep["SleepDay"] = pd.to_datetime(df_sleep["SleepDay"])

/var/folders/bk/5str535j5sq1fh6dznjr12z00000gp/T/ipykernel_2438/2342326086.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sleep["SleepDay"] = pd.to_datetime(df_sleep["SleepDay"])

In [89]:
df_sleep = df_sleep.copy()

In [90]:
df_sleep["SleepDay"] = pd.to_datetime(df_sleep["SleepDay"])

In [92]:
df_sleep["SleepDay"].dtype

dtype('<M8[ns]')

In [93]:
df_sleep["SleepDay"].min()

Timestamp('2016-04-12 00:00:00')

In [94]:
df_sleep["SleepDay"].max()

Timestamp('2016-05-12 00:00:00')

In [95]:
df_sleep["Id"].nunique()

24

In [98]:
df_sleep["Id"].count()

np.int64(410)

In [99]:
df_sleep["Id"].value_counts().min()

np.int64(1)

In [104]:
df_sleep["Id"].value_counts().max()

np.int64(31)

In [106]:
df_sleep[[
    "TotalSleepRecords",
    "TotalMinutesAsleep",
    "TotalTimeInBed"
]].describe()

       TotalSleepRecords  TotalMinutesAsleep  TotalTimeInBed
count         410.000000          410.000000      410.000000
mean            1.119512          419.173171      458.482927
std             0.346636          118.635918      127.455140
min             1.000000           58.000000       61.000000
25%             1.000000          361.000000      403.750000
50%             1.000000          432.500000      463.000000
75%             1.000000          490.000000      526.000000
max             3.000000          796.000000      961.000000

In [107]:
df_sleep[df_sleep["TotalMinutesAsleep"] > 600][
    ["Id", "SleepDay", "TotalMinutesAsleep", "TotalTimeInBed"]
]

             Id   SleepDay  TotalMinutesAsleep  TotalTimeInBed
4    1503960366 2016-04-17                 700             712
27   1644430081 2016-05-02                 796             961
29   1844505072 2016-04-15                 644             961
30   1844505072 2016-04-30                 722             961
32   1927972279 2016-04-12                 750             775
125  4319703577 2016-04-23                 692             722
138  4319703577 2016-05-08                 602             638
145  4388161847 2016-04-17                 619             641
232  5553957443 2016-04-16                 651             686
236  5553957443 2016-04-20                 658             678
239  5553957443 2016-04-23                 631             725
246  5553957443 2016-04-30                 775             843
247  5553957443 2016-05-01                 622             686
281  5577150313 2016-05-04                 603             634
299  6117666160 2016-05-06                 658             698
307  6962181067 2016-04-13                 630             679
347  7086361926 2016-04-24                 681             704
370  8378563200 2016-04-16                 611             689

In [109]:
df_sleep[
    df_sleep["TotalTimeInBed"] < df_sleep["TotalMinutesAsleep"]
].shape

(0, 5)

In [110]:
df_sleep[
    (df_sleep["TotalMinutesAsleep"] == 0) |
    (df_sleep["TotalTimeInBed"] == 0)
]

Empty DataFrame
Columns: [Id, SleepDay, TotalSleepRecords, TotalMinutesAsleep, TotalTimeInBed]
Index: []

In [111]:
df_sleep.duplicated(subset=["Id", "SleepDay"]).sum()

np.int64(0)

In [112]:
df_sleep.groupby("Id").size().describe()

count    24.000000
mean     17.083333
std      11.378533
min       1.000000
25%       4.750000
50%      20.500000
75%      27.250000
max      31.000000
dtype: float64

In [113]:
df_sleep.groupby("Id").size().sort_values().head(10)

Id
2320127002     1
7007744171     2
6775888955     3
1844505072     3
8053475328     3
1644430081     4
4558609924     5
1927972279     5
4020332650     8
8792009665    15
dtype: int64

In [114]:
df_sleep.to_csv(
    "../Cleaned_Data/sleep_cleaned.csv",
    index=False
)

In [123]:
import os

os.path.exists("../Cleaned_Data/sleep_cleaned.csv")

True

In [125]:
import os

os.listdir("../Original_Data/Fitabase Data 3.12.16-4.11.16")

['dailyActivity_merged.csv',
 'heartrate_seconds_merged.csv',
 'minuteIntensitiesNarrow_merged.csv',
 'minuteMETsNarrow_merged.csv',
 'hourlySteps_merged.csv',
 'hourlyIntensities_merged.csv',
 'hourlyCalories_merged.csv',
 'minuteSleep_merged.csv',
 'minuteCaloriesNarrow_merged.csv',
 'minuteStepsNarrow_merged.csv',
 'weightLogInfo_merged.csv']

In [126]:
import os

os.listdir("../Original_Data/Fitabase Data 3.12.16-4.11.16")

['dailyActivity_merged.csv',
 'heartrate_seconds_merged.csv',
 'minuteIntensitiesNarrow_merged.csv',
 'minuteMETsNarrow_merged.csv',
 'hourlySteps_merged.csv',
 'hourlyIntensities_merged.csv',
 'hourlyCalories_merged.csv',
 'minuteSleep_merged.csv',
 'minuteCaloriesNarrow_merged.csv',
 'minuteStepsNarrow_merged.csv',
 'weightLogInfo_merged.csv']

In [128]:
df_activity_first = pd.read_csv(
    "../Original_Data/Fitabase Data 3.12.16-4.11.16/dailyActivity_merged.csv"
)

df_activity_first.shape

(457, 15)

In [130]:
df_activity_first["ActivityDate"] = pd.to_datetime(
    df_activity_first["ActivityDate"]
)

df_activity_first["ActivityDate"].min(), df_activity_first["ActivityDate"].max()

(Timestamp('2016-03-12 00:00:00'), Timestamp('2016-04-12 00:00:00'))

In [131]:
df_activity_first["ActivityDate"].min()
df_activity_first["ActivityDate"].max()

Timestamp('2016-04-12 00:00:00')

In [132]:
df_activity_first["Id"].nunique()

35

In [133]:
len(
    set(df_activity_first["Id"]) &
    set(df_activity["Id"])
)

33

In [154]:
os.listdir("../Original_Data/Fitabase Data 3.12.16-4.11.16")

['dailyActivity_merged.csv',
 'heartrate_seconds_merged.csv',
 'minuteIntensitiesNarrow_merged.csv',
 'minuteMETsNarrow_merged.csv',
 'hourlySteps_merged.csv',
 'hourlyIntensities_merged.csv',
 'hourlyCalories_merged.csv',
 'minuteSleep_merged.csv',
 'minuteCaloriesNarrow_merged.csv',
 'minuteStepsNarrow_merged.csv',
 'weightLogInfo_merged.csv']

In [144]:
df_activity_first.isnull().sum().sum()

np.int64(0)

In [145]:
df_activity_first.duplicated().sum()

np.int64(0)

In [147]:

df_activity_first.duplicated(subset=["Id", "ActivityDate"]).sum()

np.int64(0)

In [148]:
df_activity.duplicated(
    subset=["Id", "ActivityDate"]
).sum()

np.int64(0)

In [149]:
common_april12 = pd.merge(
    df_activity_first[
        df_activity_first["ActivityDate"] == "2016-04-12"
    ],
    df_activity[
        df_activity["ActivityDate"] == "2016-04-12"
    ],
    on="Id",
    how="inner"
)

common_april12.shape

(24, 29)

In [150]:
common_april12[
    [
        "Id",
        "ActivityDate_x",
        "TotalSteps_x",
        "TotalSteps_y"
    ]
].head(10)

           Id ActivityDate_x  TotalSteps_x  TotalSteps_y
0  1503960366     2016-04-12           224         13162
1  1624580081     2016-04-12          6627          8163
2  1844505072     2016-04-12             0          6697
3  1927972279     2016-04-12            24           678
4  2022484408     2016-04-12          6717         11875
5  2026352035     2016-04-12          1019          4414
6  2320127002     2016-04-12          2098         10725
7  2347167796     2016-04-12             0         10113
8  2873212765     2016-04-12             0          8796
9  3977333714     2016-04-12           759          8856

In [151]:
common_april12[
    ["Id", "TotalSteps_x", "TotalSteps_y"]
].assign(
    same_steps=lambda x: x["TotalSteps_x"] == x["TotalSteps_y"]
)["same_steps"].value_counts()

same_steps
False    24
Name: count, dtype: int64

In [152]:
os.path.exists("../Cleaned_Data/activity_cleaned.csv")

False

In [155]:
df_activity.to_csv(
    "../Cleaned_Data/activity_cleaned.csv",
    index=False
)

In [156]:
import os

os.listdir("../Cleaned_Data")

['activity_cleaned.csv',
 'bellabeat_analysis.ipynb',
 '.venv',
 'sleep_cleaned.csv',
 '.idea']

In [157]:
os.path.exists("../Cleaned_Data/activity_cleaned.csv")

True

In [158]:
pd.read_csv("../Cleaned_Data/activity_cleaned.csv").shape

(940, 15)

In [159]:
df_activity["activity_level"] = pd.cut(
    df_activity["TotalSteps"],
    bins=[-1, 4999, 9999, float("inf")],
    labels=["Low", "Moderate", "High"]
)

In [160]:
df_activity["activity_level"].value_counts()

activity_level
Moderate    334
Low         303
High        303
Name: count, dtype: int64

In [161]:
df_activity["day_of_week"] = df_activity["ActivityDate"].dt.day_name()

In [162]:
df_activity["day_of_week"].value_counts()

day_of_week
Tuesday      152
Wednesday    150
Thursday     147
Friday       126
Saturday     124
Sunday       121
Monday       120
Name: count, dtype: int64

In [163]:
df_activity.groupby("day_of_week")["TotalSteps"].mean()

day_of_week
Friday       7448.230159
Monday       7780.866667
Saturday     8152.975806
Sunday       6933.231405
Thursday     7405.836735
Tuesday      8125.006579
Wednesday    7559.373333
Name: TotalSteps, dtype: float64

In [164]:
df_activity.groupby("activity_level")[["TotalSteps", "Calories"]].mean()

/var/folders/bk/5str535j5sq1fh6dznjr12z00000gp/T/ipykernel_2438/3321674758.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_activity.groupby("activity_level")[["TotalSteps", "Calories"]].mean()

                  TotalSteps     Calories
activity_level
Low              2128.168317  1806.811881
Moderate         7465.778443  2355.164671
High            13337.396040  2743.577558

In [165]:
df_sleep.head()

,Id,SleepDay,TotalSleepRecords,TotalMinutesAsleep,TotalTimeInBed
0,1503960366,2016-04-12,1,327,346
1,1503960366,2016-04-13,2,384,407
2,1503960366,2016-04-15,1,412,442
3,1503960366,2016-04-16,2,340,367
4,1503960366,2016-04-17,1,700,712

In [166]:
df_sleep["TotalMinutesAsleep"].mean()

np.float64(419.17317073170733)

In [167]:
df_sleep["TotalMinutesAsleep"].median()

np.float64(432.5)

In [168]:
df_activity[["Id", "ActivityDate"]].head()

           Id ActivityDate
0  1503960366   2016-04-12
1  1503960366   2016-04-13
2  1503960366   2016-04-14
3  1503960366   2016-04-15
4  1503960366   2016-04-16

In [169]:
df_sleep[["Id", "SleepDay"]].head()

           Id   SleepDay
0  1503960366 2016-04-12
1  1503960366 2016-04-13
2  1503960366 2016-04-15
3  1503960366 2016-04-16
4  1503960366 2016-04-17

In [173]:
df_activity_sleep = pd.merge(
    df_activity,
    df_sleep,
    left_on=["Id", "ActivityDate"],
    right_on=["Id", "SleepDay"],
    how="inner"
)

In [174]:
df_activity_sleep.shape

(410, 21)

In [175]:
df_activity_sleep.head()

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,...,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories,activity_level,day_of_week,SleepDay,TotalSleepRecords,TotalMinutesAsleep,TotalTimeInBed
0,1503960366,2016-04-12,13162,8.50,8.50,0.0,1.88,0.55,6.06,0.0,...,13,328,728,1985,High,Tuesday,2016-04-12,1,327,346
1,1503960366,2016-04-13,10735,6.97,6.97,0.0,1.57,0.69,4.71,0.0,...,19,217,776,1797,High,Wednesday,2016-04-13,2,384,407
2,1503960366,2016-04-15,9762,6.28,6.28,0.0,2.14,1.26,2.83,0.0,...,34,209,726,1745,Moderate,Friday,2016-04-15,1,412,442
3,1503960366,2016-04-16,12669,8.16,8.16,0.0,2.71,0.41,5.04,0.0,...,10,221,773,1863,High,Saturday,2016-04-16,2,340,367
4,1503960366,2016-04-17,9705,6.48,6.48,0.0,3.19,0.78,2.51,0.0,...,20,164,539,1728,Moderate,Sunday,2016-04-17,1,700,712

In [176]:
df_activity_sleep["sleep_category"] = pd.cut(
    df_activity_sleep["TotalMinutesAsleep"],
    bins=[0, 359, 479, float("inf")],
    labels=["Less than 6 hours", "6–8 hours", "More than 8 hours"]
)

In [177]:
df_activity_sleep.groupby("sleep_category", observed=True)["TotalSteps"].mean()

sleep_category
Less than 6 hours    9484.030000
6–8 hours            8761.252577
More than 8 hours    7267.474138
Name: TotalSteps, dtype: float64

In [178]:
df_activity_sleep["sleep_category"].value_counts()

sleep_category
6–8 hours            194
More than 8 hours    116
Less than 6 hours    100
Name: count, dtype: int64

In [179]:
df_activity_sleep.groupby("sleep_category", observed=True)["Calories"].mean()

sleep_category
Less than 6 hours    2262.250000
6–8 hours            2524.804124
More than 8 hours    2272.189655
Name: Calories, dtype: float64

In [180]:
df_activity_sleep[["TotalMinutesAsleep", "TotalSteps"]].corr()

                    TotalMinutesAsleep  TotalSteps
TotalMinutesAsleep            1.000000   -0.190344
TotalSteps                   -0.190344    1.000000

In [181]:
df_activity[
    [
        "TotalSteps",
        "VeryActiveMinutes",
        "FairlyActiveMinutes",
        "LightlyActiveMinutes",
        "SedentaryMinutes"
    ]
].mean()

TotalSteps              7637.910638
VeryActiveMinutes         21.164894
FairlyActiveMinutes       13.564894
LightlyActiveMinutes     192.812766
SedentaryMinutes         991.210638
dtype: float64

In [182]:
df_activity["SedentaryMinutes"].describe()

count     940.000000
mean      991.210638
std       301.267437
min         0.000000
25%       729.750000
50%      1057.500000
75%      1229.500000
max      1440.000000
Name: SedentaryMinutes, dtype: float64

In [183]:
pd.cut(
    df_activity["SedentaryMinutes"],
    bins=[-1, 719, 1079, 1439, 1440],
    labels=[
        "Less than 12 hours",
        "12–18 hours",
        "18–24 hours",
        "Exactly 24 hours"
    ]
).value_counts()

SedentaryMinutes
18–24 hours           366
12–18 hours           282
Less than 12 hours    213
Exactly 24 hours       79
Name: count, dtype: int64

In [184]:
df_activity_sleep.to_csv(
    "../Cleaned_Data/activity_sleep_cleaned.csv",
    index=False
)

In [185]:
pd.read_csv("../Cleaned_Data/activity_sleep_cleaned.csv").shape

(410, 22)

In [186]:
df_activity_sleep.columns

Index(['Id', 'ActivityDate', 'TotalSteps', 'TotalDistance', 'TrackerDistance',
       'LoggedActivitiesDistance', 'VeryActiveDistance',
       'ModeratelyActiveDistance', 'LightActiveDistance',
       'SedentaryActiveDistance', 'VeryActiveMinutes', 'FairlyActiveMinutes',
       'LightlyActiveMinutes', 'SedentaryMinutes', 'Calories',
       'activity_level', 'day_of_week', 'SleepDay', 'TotalSleepRecords',
       'TotalMinutesAsleep', 'TotalTimeInBed', 'sleep_category'],
      dtype='object')

In [187]:
tableau_columns = [
    "Id",
    "ActivityDate",
    "TotalSteps",
    "VeryActiveMinutes",
    "FairlyActiveMinutes",
    "LightlyActiveMinutes",
    "SedentaryMinutes",
    "Calories",
    "activity_level",
    "day_of_week",
    "TotalMinutesAsleep",
    "TotalTimeInBed",
    "sleep_category"
]

df_tableau = df_activity_sleep[tableau_columns].copy()

In [188]:
df_tableau.shape

(410, 13)

In [189]:
df_tableau.to_csv(
    "../Cleaned_Data/bellabeat_tableau.csv",
    index=False
)

In [190]:
import os

os.path.exists("../Cleaned_Data/bellabeat_tableau.csv")

True

In [191]:
df_tableau.to_csv("../Cleaned_Data/bellabeat_tableau.csv", index=False)